const lessonData = {};

lessonData["01_GreatPyramid.mp3"] = [{
    text: "1. The Great Pyramid of Giza. The Great Pyramid of Giza is a very famous monument in Egypt. It is near the city of Cairo. People built it a very long time ago, around 4,500 years ago. It was built for a king named Khufu. He was a pharaoh in ancient Egypt. The pyramid is huge. For a very long time, it was the tallest building in the world. It is about 147 meters tall. Workers used millions of heavy stone blocks to build it. It was very hard work. Today, many tourists travel to Egypt to see this amazing pyramid. They like to take photos of it. The Great Pyramid is special because it is the oldest of the Seven Wonders of the Ancient World. It is also the only ancient wonder that is still standing today. Inside the pyramid, there are dark rooms and long tunnels. The king was buried inside one of these rooms. People still study the Great Pyramid today. They want to learn how the ancient Egyptians built such a big and perfect building without modern machines. It is a wonderful place.",
    dict: { "monument": "anıt", "pharaoh": "firavun", "heavy": "ağır", "blocks": "bloklar", "tourists": "turistler", "standing": "ayakta duran", "tunnels": "tüneller", "buried": "gömülü", "machines": "makineler" },
    questions: [ {q:"Is the Great Pyramid in Egypt?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it built for King Khufu?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it the tallest building for a long time?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it the newest of the Seven Wonders?", a_en:"No", a_tr:"Hayır"}, {q:"Are there dark rooms inside?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the king buried inside?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use modern machines to build it?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["02_GreatWall.mp3"] = [{
    text: "2. The Great Wall of China. The Great Wall of China is one of the biggest building projects in history. It is a very long wall in the north part of China. The Chinese people built it a long time ago. They started building it more than 2,000 years ago. They built the wall to protect their country from enemies. Different emperors added to the wall over many years. It is not just one long wall. It is made of many walls joined together. It is thousands of kilometers long. It goes across mountains, deserts, and rivers. Soldiers stood on the wall to watch for danger. They used fire and smoke to send messages to other soldiers. Millions of people worked to build the Great Wall. Many of them died because the work was very hard and dangerous. Today, the Great Wall of China is a very famous place. Millions of tourists visit it every year. People love to walk on the wall and look at the beautiful mountains. You can see how strong and clever the ancient Chinese people were when you visit this amazing place.",
    dict: { "history": "tarih", "protect": "korumak", "enemies": "düşmanlar", "emperors": "imparatorlar", "joined": "birleştirilmiş", "deserts": "çöller", "soldiers": "askerler", "danger": "tehlike", "smoke": "duman", "messages": "mesajlar" },
    questions: [ {q:"Is the Great Wall in the south part of China?", a_en:"No", a_tr:"Hayır"}, {q:"Did they build it to protect from enemies?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it just one long wall?", a_en:"No", a_tr:"Hayır"}, {q:"Did soldiers stand on the wall?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they use fire and smoke to send messages?", a_en:"Yes", a_tr:"Evet"}, {q:"Did millions of people work to build it?", a_en:"Yes", a_tr:"Evet"}, {q:"Can you walk on the wall today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_TajMahal.mp3"] = [{
    text: "3. The Taj Mahal. The Taj Mahal is a beautiful building in the city of Agra, in India. It is one of the most famous monuments in the whole world. It is made of shiny white marble stone. A rich emperor named Shah Jahan built the Taj Mahal. He built it a long time ago, in the 17th century. He built it because he loved his wife very much. When his wife died, the emperor was very sad. He wanted to make a special place for her to rest forever. It took more than twenty years to finish the Taj Mahal. Thousands of workers and artists helped to build it. They brought beautiful stones from all over Asia to decorate the white marble walls. The building looks different at different times of the day. Sometimes it looks pink in the morning, and sometimes it looks silver at night under the moon. There is a big, beautiful garden and a long pool of water in front of it. Millions of people travel to India every year just to see the beautiful Taj Mahal.",
    dict: { "shiny": "parlak", "marble": "mermer", "emperor": "imparator", "sad": "üzgün", "rest forever": "sonsuza dek dinlenmek", "artists": "sanatçılar", "decorate": "süslemek", "pink": "pembe", "silver": "gümüş", "pool": "havuz" },
    questions: [ {q:"Is the Taj Mahal in India?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it made of black stone?", a_en:"No", a_tr:"Hayır"}, {q:"Did Shah Jahan build it?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he build it because he loved his wife?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it take more than twenty years to finish?", a_en:"Yes", a_tr:"Evet"}, {q:"Does it look pink in the morning?", a_en:"Yes", a_tr:"Evet"}, {q:"Is there a long pool of water in front of it?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_Colosseum.mp3"] = [{
    text: "4. The Colosseum. The Colosseum is a very old and famous building in the center of Rome, Italy. It is a huge amphitheater. The ancient Romans built it almost two thousand years ago. It is made of stone and concrete. When it was new, it was very big and strong. It could hold about fifty thousand people inside. People went to the Colosseum to watch shows and games. The most famous shows were the gladiator fights. Gladiators were strong men who fought each other. Sometimes they fought wild animals like lions and bears. The people of Rome loved to watch these exciting but dangerous games. The emperor of Rome sat in a special place to watch the shows. Today, the Colosseum is partly broken because of old earthquakes and people taking the stones. But it is still a very important symbol of the Roman Empire. It shows how good the Romans were at building big things. Many tourists from all over the world visit the Colosseum every day. They walk inside and imagine what the games were like a long time ago.",
    dict: { "amphitheater": "amfitiyatro", "concrete": "beton", "gladiator": "gladyatör", "fought": "dövüştü", "wild animals": "vahşi hayvanlar", "exciting": "heyecan verici", "dangerous": "tehlikeli", "earthquakes": "depremler", "symbol": "sembol", "imagine": "hayal etmek" },
    questions: [ {q:"Is the Colosseum in Rome?", a_en:"Yes", a_tr:"Evet"}, {q:"Could it hold fifty thousand people?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people go there to watch gladiator fights?", a_en:"Yes", a_tr:"Evet"}, {q:"Did gladiators fight wild animals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the emperor sit in a special place?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Colosseum completely perfect today?", a_en:"No", a_tr:"Hayır"}, {q:"Is it a symbol of the Roman Empire?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_MachuPicchu.mp3"] = [{
    text: "5. Machu Picchu. Machu Picchu is a beautiful ancient city in the country of Peru. It is high up in the Andes Mountains. The Inca people built this city a long time ago, in the 15th century. They built it on a tall mountain above a river. Machu Picchu is very special because the Spanish soldiers never found it when they came to South America. Because of this, the city was not destroyed. For hundreds of years, the city was empty and quiet. Plants and trees grew over the buildings. In the year 1911, an explorer named Hiram Bingham found the city again. Today, we call it the 'Lost City of the Incas.' The buildings in Machu Picchu are made of large stones. The Inca builders were very clever. They cut the stones perfectly so they fit together without any mud or cement. The city has many houses, temples, and places for farming on the side of the mountain. People can travel by train or walk for many days on the Inca Trail to visit this beautiful and mysterious mountain city.",
    dict: { "ancient": "antik/eski", "destroyed": "yok edildi/yıkıldı", "empty": "boş", "explorer": "kaşif", "clever": "zeki", "fit together": "birbirine uymak", "cement": "çimento", "temples": "tapınaklar", "farming": "çiftçilik", "mysterious": "gizemli" },
    questions: [ {q:"Is Machu Picchu in the Andes Mountains?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Inca people build it?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Spanish soldiers find it and destroy it?", a_en:"No", a_tr:"Hayır"}, {q:"Did Hiram Bingham find the city again?", a_en:"Yes", a_tr:"Evet"}, {q:"Do we call it the Lost City of the Incas?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the builders use cement for the stones?", a_en:"No", a_tr:"Hayır"}, {q:"Can people travel there by train?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_Acropolis.mp3"] = [{
    text: "6. The Acropolis of Athens. The Acropolis of Athens is a very important historical place in Greece. It is a group of old, beautiful buildings on top of a high rocky hill in the city of Athens. The ancient Greeks built these monuments more than two thousand years ago. The most famous building on the Acropolis is the Parthenon. It is a big temple with many tall stone columns. The Greeks built the Parthenon for Athena. Athena was the goddess of wisdom, and the city of Athens was named after her. Inside the temple, there was a very big and rich statue of the goddess made of gold and ivory. The Acropolis was a safe place for the people of Athens during wars. It was also a place for religion and big festivals. Over the years, the buildings were damaged by wars, time, and weather. But people are working hard to fix them and keep them safe. Today, the Acropolis is a famous symbol of ancient Greece and its ideas about democracy and art. Millions of tourists climb the hill every year.",
    dict: { "rocky hill": "kayalık tepe", "columns": "sütunlar", "goddess": "tanrıça", "wisdom": "bilgelik", "ivory": "fildişi", "religion": "din", "festivals": "festivaller", "damaged": "hasar görmüş", "democracy": "demokrasi", "climb": "tırmanmak" },
    questions: [ {q:"Is the Acropolis in Greece?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Parthenon a big temple there?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the Parthenon built for Athena?", a_en:"Yes", a_tr:"Evet"}, {q:"Was Athena the goddess of wisdom?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the statue of Athena made of wood?", a_en:"No", a_tr:"Hayır"}, {q:"Was the Acropolis a safe place during wars?", a_en:"Yes", a_tr:"Evet"}, {q:"Do millions of tourists climb the hill every year?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_Petra.mp3"] = [{
    text: "7. Petra. Petra is an amazing ancient city in the country of Jordan. It is very famous because it is not built with normal stones. Instead, the buildings are carved directly into the high red rock walls of a canyon. Because of the red color of the stone, people often call Petra the 'Rose City.' A group of people called the Nabataeans built this city more than two thousand years ago. They were very smart and knew how to collect and keep water in the dry desert. Petra became a very rich city because many people traveled through it to buy and sell things. The most famous building in Petra is called the Treasury. It has a very beautiful front wall with tall columns, all cut from the solid rock. For a long time, people from other parts of the world did not know about Petra. It was a secret city in the desert. Then, in the year 1812, a Swiss traveler found it again. Today, tourists love to walk through the narrow canyon to see this beautiful and unique place.",
    dict: { "carved": "oyulmuş", "directly": "doğrudan", "canyon": "kanyon", "desert": "çöl", "collect": "toplamak", "solid rock": "katı kaya/yekpare kaya", "secret": "gizli", "traveler": "gezgin", "narrow": "dar", "unique": "eşsiz/benzersiz" },
    questions: [ {q:"Is Petra built with normal stones?", a_en:"No", a_tr:"Hayır"}, {q:"Are the buildings carved into the red rock walls?", a_en:"Yes", a_tr:"Evet"}, {q:"Do people call it the Rose City?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Nabataeans build it?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the most famous building called the Treasury?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people from other parts of the world always know about Petra?", a_en:"No", a_tr:"Hayır"}, {q:"Do tourists walk through a narrow canyon to see it?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_ChichenItza.mp3"] = [{
    text: "8. Chichén Itzá. Chichén Itzá is a famous ancient city in Mexico. It is located on the Yucatán Peninsula. The Maya people built this big city more than a thousand years ago. It was a very important center for religion, business, and daily life. The Maya people were very good at building and studying the stars. The most famous building in Chichén Itzá is a big pyramid called El Castillo. It is also known as the Temple of Kukulcan. This pyramid is very special because it is like a big stone calendar. It has four sides with stairs. If you count all the steps and the top platform, there are 365 steps. This is the same as the number of days in a year. Twice a year, when the sun shines on the pyramid in a special way, a shadow looks like a giant snake moving down the stairs. The city also has a very large court where the Maya people played an important ball game. Today, Chichén Itzá is a very popular place for tourists who want to learn about Maya history.",
    dict: { "located": "konumlanmış/yer alır", "peninsula": "yarımada", "religion": "din", "pyramid": "piramit", "calendar": "takvim", "top platform": "üst platform", "shadow": "gölge", "giant": "dev", "snake": "yılan", "court": "saha/oyun alanı" },
    questions: [ {q:"Is Chichén Itzá an ancient city in Mexico?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Maya people build it?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the famous building a big pyramid called El Castillo?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the pyramid have 365 steps?", a_en:"Yes", a_tr:"Evet"}, {q:"Does a shadow look like a giant snake twice a year?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Maya people play an important ball game there?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it a good place to learn about Roman history?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["09_Stonehenge.mp3"] = [{
    text: "9. Stonehenge. Stonehenge is a very old and famous monument in the United Kingdom. It is in a big green field in England. Stonehenge is a circle of very large and heavy standing stones. Some of these stones are more than four meters tall. People built Stonehenge a very, very long time ago. They started building it around five thousand years ago. Building it took hundreds of years. The interesting thing is that people still do not know exactly why it was built. Some people think it was a special place for religion and ceremonies. Other people think it was an old kind of calendar to study the sun and the stars. The stones are very heavy. It is a big mystery how the ancient people moved these giant stones without modern machines or trucks. Some stones came from places very far away. Today, Stonehenge is a very popular place to visit. Many people like to go there on the longest and shortest days of the year to watch the sunrise and sunset behind the giant, ancient stones.",
    dict: { "field": "tarla/alan", "standing stones": "dikili taşlar", "heavy": "ağır", "interesting": "ilginç", "ceremonies": "törenler", "mystery": "gizem", "giant": "dev", "sunrise": "gün doğumu", "sunset": "gün batımı" },
    questions: [ {q:"Is Stonehenge in the United Kingdom?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it a square of very large stones?", a_en:"No", a_tr:"Hayır"}, {q:"Did people start building it 5,000 years ago?", a_en:"Yes", a_tr:"Evet"}, {q:"Do we know exactly why it was built?", a_en:"No", a_tr:"Hayır"}, {q:"Did the ancient people use trucks to move the stones?", a_en:"No", a_tr:"Hayır"}, {q:"Did some stones come from far away?", a_en:"Yes", a_tr:"Evet"}, {q:"Do people watch the sunrise and sunset there?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_HagiaSophia.mp3"] = [{
    text: "10. Hagia Sophia. Hagia Sophia is a very famous and beautiful building in Istanbul, Turkey. It has a very long and interesting history. It was built a long time ago, in the year 537. The emperor Justinian built it. At first, it was a very big Christian church. For almost a thousand years, it was the largest church in the world. It has a huge and amazing dome on the top. People thought the dome looked like it was hanging from the sky. Later, in the year 1453, the city was taken by the Ottoman Empire. The new rulers changed Hagia Sophia into a beautiful mosque. They added four tall minarets on the outside. They also covered some of the old pictures inside and added Islamic art. After many years, in 1935, the building became a museum so everyone could see its beauty. Recently, it became a mosque again. Hagia Sophia is very important because it shows the art and history of both the Byzantine and Ottoman empires. It is one of the most popular places to visit in Istanbul today.",
    dict: { "interesting": "ilginç", "dome": "kubbe", "hanging": "asılı duran", "rulers": "yöneticiler", "mosque": "cami", "minarets": "minareler", "covered": "kapladılar/örttüler", "museum": "müze", "beauty": "güzellik", "recently": "son zamanlarda" },
    questions: [ {q:"Is Hagia Sophia in Istanbul, Turkey?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it a very big Christian church at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it the largest church in the world for a thousand years?", a_en:"Yes", a_tr:"Evet"}, {q:"Does it have a huge dome on the top?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Ottoman Empire change it into a mosque?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it ever become a museum?", a_en:"Yes", a_tr:"Evet"}, {q:"Does it show the art of the Byzantine and Ottoman empires?", a_en:"Yes", a_tr:"Evet"} ]
}];lessonData["11_EiffelTower.mp3"] = [{
    text: "11. The Eiffel Tower. The Eiffel Tower is a very famous metal tower in Paris, France. It is the most famous symbol of the city. A man named Gustave Eiffel built it for a big world exhibition in the year 1889. It is made of strong iron. When it was finished, it was the tallest building in the whole world. It is about 330 meters tall today. At first, many people in Paris did not like the tower. They thought it was ugly and looked like a giant factory chimney. They wanted to take it down after the exhibition. But later, people started to love it. It was also very useful for sending radio and telegraph signals. Today, the Eiffel Tower is loved by people all over the world. Millions of tourists visit it every year. You can take an elevator or walk up many stairs to reach the top. From the top, you can see the beautiful city of Paris, the river Seine, and many other famous places. At night, the tower sparkles with thousands of bright lights.",
    dict: { "exhibition": "sergi/fuar", "iron": "demir", "ugly": "çirkin", "chimney": "baca", "useful": "kullanışlı", "signals": "sinyaller", "elevator": "asansör", "sparkles": "parıldar" },
    questions: [ {q:"Is the Eiffel Tower in Paris, France?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Gustave Eiffel build it for a world exhibition?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it made of wood?", a_en:"No", a_tr:"Hayır"}, {q:"Did everyone in Paris love it at first?", a_en:"No", a_tr:"Hayır"}, {q:"Was it useful for sending radio signals?", a_en:"Yes", a_tr:"Evet"}, {q:"Can you take an elevator to the top?", a_en:"Yes", a_tr:"Evet"}, {q:"Does it sparkle with bright lights at night?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_AngkorWat.mp3"] = [{
    text: "12. Angkor Wat. Angkor Wat is a huge and beautiful temple complex in Cambodia. It is the largest religious monument in the whole world. A king named Suryavarman II built it a long time ago, in the 12th century. At first, it was built as a Hindu temple for the god Vishnu. Later, it changed and became a Buddhist temple. The temple is very big and has a large wall and a deep moat full of water around it. The main building has five tall towers shaped like lotus flowers. The walls of Angkor Wat are covered with beautiful stone carvings. These carvings show stories from old religions and history. They also show what daily life was like a long time ago. For many years, the temple was hidden in the jungle. Huge trees and plants grew over the stone walls. Today, people have cleared the jungle, and tourists can visit this amazing place. Angkor Wat is a very important symbol of Cambodia. A picture of the temple is even painted on the national flag of the country.",
    dict: { "complex": "kompleks/tesis", "religious": "dini", "moat": "hendek", "lotus": "nilüfer", "carvings": "oymalar/kabartmalar", "hidden": "gizli", "jungle": "orman", "cleared": "temizlediler" },
    questions: [ {q:"Is Angkor Wat a huge temple complex in Cambodia?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it built as a Hindu temple at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the main building have towers shaped like lotus flowers?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the walls covered with beautiful stone carvings?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the temple hidden in the desert for many years?", a_en:"No", a_tr:"Hayır"}, {q:"Did huge trees and plants grow over the walls?", a_en:"Yes", a_tr:"Evet"}, {q:"Is a picture of the temple on the national flag?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_Alhambra.mp3"] = [{
    text: "13. The Alhambra. The Alhambra is a beautiful palace and fortress in the city of Granada, in Spain. It sits high on a hill overlooking the city. The name 'Alhambra' means 'Red Castle' in Arabic because of the color of its outside walls. Muslim rulers built most of this amazing palace in the 13th and 14th centuries. The Alhambra is very famous for its incredible Islamic art and architecture. Inside the palace, there are many beautiful rooms with very detailed carvings on the walls and ceilings. The floors have colorful tiles with pretty patterns. Water is also a very important part of the Alhambra. There are lovely courtyards with quiet pools, relaxing fountains, and small rivers. The most famous courtyard is the Court of the Lions. It has a beautiful fountain supported by twelve stone lions. The palace also has wonderful green gardens filled with flowers and trees. The Alhambra is a very special place because it shows the rich history and culture of the Muslim period in Spain. Many tourists visit it to see its beauty and peaceful gardens.",
    dict: { "fortress": "kale", "overlooking": "tepeden bakan", "architecture": "mimari", "detailed": "detaylı", "ceilings": "tavanlar", "tiles": "fayanslar/karolar", "patterns": "desenler", "courtyards": "avlular", "fountains": "çeşmeler" },
    questions: [ {q:"Is the Alhambra in Spain?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the name mean 'Red Castle' in Arabic?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Muslim rulers build most of this palace?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the floors covered with colorful tiles?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the Court of the Lions a famous courtyard?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the fountain supported by fifty stone lions?", a_en:"No", a_tr:"Hayır"}, {q:"Does it have wonderful green gardens?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_Versailles.mp3"] = [{
    text: "14. Palace of Versailles. The Palace of Versailles is a very big and rich palace in France. It is located near the city of Paris. A long time ago, it was a simple hunting lodge. But in the 17th century, King Louis XIV changed it. He wanted to show everyone how powerful and rich he was. He made it into a huge, magnificent palace. The King moved his home and his government to Versailles. The palace has more than two thousand rooms. The most famous room is the Hall of Mirrors. It is a long, beautiful room with seventeen very large mirrors on one side and big windows on the other. The palace is decorated with a lot of gold, expensive paintings, and rich furniture. Outside the palace, there are enormous, beautiful gardens. The gardens have thousands of trees, colorful flowers, and many wonderful fountains with statues. The Kings of France lived there until the French Revolution started in 1789. Today, the Palace of Versailles is a very popular museum. Millions of people visit to see how the French kings lived.",
    dict: { "hunting lodge": "av köşkü", "powerful": "güçlü", "magnificent": "muhteşem", "mirrors": "aynalar", "decorated": "süslenmiş", "furniture": "mobilya", "enormous": "devasa", "statues": "heykeller" },
    questions: [ {q:"Is the Palace of Versailles in France?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it a simple hunting lodge a long time ago?", a_en:"Yes", a_tr:"Evet"}, {q:"Did King Louis XIV make it into a huge palace?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the palace have only twenty rooms?", a_en:"No", a_tr:"Hayır"}, {q:"Is the Hall of Mirrors a famous room there?", a_en:"Yes", a_tr:"Evet"}, {q:"Are there enormous gardens outside the palace?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Kings of France live there until 1789?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_ForbiddenCity.mp3"] = [{
    text: "15. The Forbidden City. The Forbidden City is a huge and very famous palace complex in the center of Beijing, China. It is called 'forbidden' because, for a very long time, normal people were not allowed to go inside. Only the Emperor, his family, and his special workers could live there. It was built hundreds of years ago, starting in the year 1406. For almost five hundred years, it was the home of twenty-four different Chinese emperors. The Forbidden City is very big. It has almost one thousand buildings and thousands of rooms. A high red wall and a wide river protect the palace. The buildings are made of wood and have special yellow roofs. Yellow was the color of the emperor. Inside the walls, there are many beautiful courtyards, big halls, and peaceful gardens. The emperor managed the country from these great halls. Today, there are no more emperors in China. The Forbidden City is now a very famous museum. Visitors from all over the world come to see the beautiful buildings and learn about Chinese history.",
    dict: { "forbidden": "yasak", "emperors": "imparatorlar", "roofs": "çatılar", "managed": "yönetti", "visitors": "ziyaretçiler" },
    questions: [ {q:"Is the Forbidden City in Beijing, China?", a_en:"Yes", a_tr:"Evet"}, {q:"Were normal people allowed to go inside for a long time?", a_en:"No", a_tr:"Hayır"}, {q:"Was it the home of Chinese emperors?", a_en:"Yes", a_tr:"Evet"}, {q:"Does it have almost one thousand buildings?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the buildings have special yellow roofs?", a_en:"Yes", a_tr:"Evet"}, {q:"Was yellow the color of the emperor?", a_en:"Yes", a_tr:"Evet"}, {q:"Are there still emperors living there today?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["16_GreatSphinx.mp3"] = [{
    text: "16. The Great Sphinx of Giza. The Great Sphinx of Giza is a very famous and old statue in Egypt. It is located very close to the Great Pyramid of Giza. The Sphinx is a giant creature made of stone. It has the body of a big lion and the head of a human man. Many people think the face of the Sphinx belongs to an ancient Egyptian king named Khafre. People built this amazing statue a very long time ago, around 4,500 years ago. It is one of the oldest and largest statues in the world. The Sphinx was carved out of one very large piece of solid rock. It is about twenty meters tall and more than seventy meters long. The lion body means power and strength, and the human head means wisdom. For a very long time, the body of the Sphinx was hidden under the desert sand. Only its head was showing. Later, people dug the sand away so we can see the whole statue. Today, it stands proudly in the desert, looking towards the sunrise every morning.",
    dict: { "creature": "yaratık", "human": "insan", "wisdom": "bilgelik", "hidden": "gizli", "sand": "kum", "dug": "kazdılar", "proudly": "gururla", "sunrise": "gün doğumu" },
    questions: [ {q:"Is the Great Sphinx close to the Great Pyramid?", a_en:"Yes", a_tr:"Evet"}, {q:"Does it have the body of a lion and the head of a man?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it a very small statue?", a_en:"No", a_tr:"Hayır"}, {q:"Was it carved out of one large piece of rock?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the human head mean wisdom?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the body hidden under the desert sand for a long time?", a_en:"Yes", a_tr:"Evet"}, {q:"Does it look towards the sunset every evening?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["17_StatueOfLiberty.mp3"] = [{
    text: "17. The Statue of Liberty. The Statue of Liberty is a very famous and important monument in the United States. It stands on a small island in the water near New York City. The statue is a very tall woman wearing a long dress. She is holding a bright torch high in her right hand. In her left hand, she holds a book with the date of American independence. The statue is made of copper metal, which turned green over many years. The people of France gave the statue to the United States in the year 1886. It was a wonderful gift to celebrate friendship and freedom. A man named Frederic-Auguste Bartholdi designed the statue, and Gustave Eiffel helped build the strong metal frame inside. For many years, when immigrants traveled by ship to live in America, the Statue of Liberty was the first thing they saw. It gave them hope for a new and better life. Today, visitors can take a boat to the island. They can climb up inside the statue to look at the beautiful city views.",
    dict: { "torch": "meşale", "independence": "bağımsızlık", "copper metal": "bakır madeni", "friendship": "arkadaşlık", "freedom": "özgürlük", "immigrants": "göçmenler", "hope": "umut" },
    questions: [ {q:"Is the Statue of Liberty near New York City?", a_en:"Yes", a_tr:"Evet"}, {q:"Is she holding a bright torch in her right hand?", a_en:"Yes", a_tr:"Evet"}, {q:"Is the statue made of copper metal?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the people of France give it to the United States?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it a gift to celebrate friendship and freedom?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Gustave Eiffel help build the inside frame?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it give immigrants hope for a new life?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_ChristRedeemer.mp3"] = [{
    text: "18. Christ the Redeemer. Christ the Redeemer is a very famous and tall statue in the city of Rio de Janeiro, in Brazil. It is a large statue of Jesus Christ. The statue stands at the very top of a high mountain called Corcovado. Because it is so high up, you can see the statue from almost anywhere in the big city. The statue was finished in the year 1931. It is made of concrete and covered with millions of small soapstone tiles. These tiles protect the statue from rain and wind. The statue is about thirty meters tall, and its arms are open very wide. The open arms show love, peace, and welcoming to all the people of Brazil and the world. To visit the statue, people can take a special small train up the steep mountain. When tourists reach the top, they can see a beautiful view of the city, the ocean, and the beaches below. Christ the Redeemer is a very important symbol of Brazilian culture and a famous wonder of the modern world.",
    dict: { "concrete": "beton", "tiles": "fayanslar/karolar", "peace": "barış", "welcoming": "karşılama/hoş geldin", "steep": "dik", "ocean": "okyanus", "view": "manzara" },
    questions: [ {q:"Is Christ the Redeemer in Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Does it stand at the top of a high mountain?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it covered with millions of small soapstone tiles?", a_en:"Yes", a_tr:"Evet"}, {q:"Do the open arms show love and peace?", a_en:"Yes", a_tr:"Evet"}, {q:"Can people take a small train up the mountain?", a_en:"Yes", a_tr:"Evet"}, {q:"Can you see a beautiful view of the city from the top?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it a symbol of French culture?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["19_Moai.mp3"] = [{
    text: "19. Moai of Easter Island. The Moai are very famous and strange stone statues on Easter Island. This small island is very far away in the Pacific Ocean and belongs to the country of Chile. The statues are huge, heavy faces and bodies carved out of volcanic rock. The native people of the island, called the Rapa Nui, made these statues hundreds of years ago. There are almost one thousand Moai statues on the island. Some of them are very tall, almost ten meters high. The people carved them in a place with a lot of rock and then moved them near the ocean. They put the statues on big stone platforms facing the villages. People think the statues represent important old leaders and ancestors. It is a big mystery how the people moved these very heavy stone statues without any wheels or modern machines. Many people study the island to learn how they did it. Today, Easter Island is a quiet and beautiful place. Tourists travel very far across the ocean just to see these amazing and mysterious giant stone faces.",
    dict: { "volcanic rock": "volkanik kaya", "native": "yerli", "platforms": "platformlar", "facing": "dönük/yönelik", "represent": "temsil etmek", "ancestors": "atalar", "mystery": "gizem" },
    questions: [ {q:"Are the Moai stone statues on Easter Island?", a_en:"Yes", a_tr:"Evet"}, {q:"Are they carved out of volcanic rock?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Rapa Nui people make them?", a_en:"Yes", a_tr:"Evet"}, {q:"Are there only ten statues on the island?", a_en:"No", a_tr:"Hayır"}, {q:"Do they face the villages?", a_en:"Yes", a_tr:"Evet"}, {q:"Do people think they represent old leaders and ancestors?", a_en:"Yes", a_tr:"Evet"}, {q:"Is it a mystery how they moved the heavy stones?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_Pantheon.mp3"] = [{
    text: "20. The Pantheon. The Pantheon is a wonderful and very old building in Rome, Italy. It was built almost two thousand years ago by the ancient Romans. At first, it was a temple for all the different Roman gods. Later, it became a Christian church. Because people used it all the time, it is one of the best-kept ancient buildings in the world today. The front of the Pantheon has a porch with very tall stone columns. But the most amazing part is inside. There is a huge, round room with a very big dome ceiling. This dome is made of concrete. For hundreds of years, it was the largest dome in the whole world. At the very top of the dome, there is a large round hole called the oculus. The hole is open to the sky. It lets bright sunshine into the building, but it also lets the rain come in! Many famous people from history, like artists and kings, are buried inside the Pantheon. It is a very beautiful place that shows how smart Roman builders were.",
    dict: { "temple": "tapınak", "gods": "tanrılar", "best-kept": "en iyi korunmuş", "porch": "veranda/sundurma", "dome ceiling": "kubbeli tavan", "oculus": "oculus/göz", "buried": "gömülü" },
    questions: [ {q:"Is the Pantheon in Rome, Italy?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it a temple for all the Roman gods at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it later become a Christian church?", a_en:"Yes", a_tr:"Evet"}, {q:"Is there a huge, round room with a big dome inside?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it the largest dome in the world for hundreds of years?", a_en:"Yes", a_tr:"Evet"}, {q:"Is there a large round hole called the oculus at the top?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the hole stop the rain from coming in?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["21_Neuschwanstein.mp3"] = [{
    text: "21. Neuschwanstein Castle. Neuschwanstein Castle is a beautiful and very famous castle in Germany. It is located in the region of Bavaria, up on a high hill surrounded by big green mountains and dark forests. The castle looks like it comes from a fairy tale. In fact, Walt Disney used this castle as an idea for his famous sleeping beauty castle. King Ludwig II of Bavaria built this castle in the late 19th century. He was a very shy king who loved art, music, and old stories about knights. He did not build the castle for defense or war. He built it as a quiet, private place to hide from the public. He wanted the castle to look like a magical place from the past. The castle has tall towers and beautiful rooms inside, decorated with gold and expensive paintings. Sadly, the king died before the castle was completely finished. Shortly after he died, the castle was opened to the public. Today, millions of tourists travel to the mountains of Germany to visit this beautiful, romantic, and magical castle.",
    dict: { "region": "bölge", "surrounded": "çevrili", "fairy tale": "peri masalı", "shy": "utangaç", "knights": "şövalyeler", "defense": "savunma", "romantic": "romantik", "magical": "büyülü" },
    questions: [ {q:"Is Neuschwanstein Castle in Germany?", a_en:"Yes", a_tr:"Evet"}, {q:"Does it look like it comes from a fairy tale?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Walt Disney use it as an idea for a castle?", a_en:"Yes", a_tr:"Evet"}, {q:"Did King Ludwig II build it for defense or war?", a_en:"No", a_tr:"Hayır"}, {q:"Did he want a quiet, private place to hide?", a_en:"Yes", a_tr:"Evet"}, {q:"Are the rooms decorated with gold and paintings?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the king live there for fifty years?", a_en:"No", a_tr:"Hayır"} ]
}];
